#!/usr/bin/python3

import ev3dev.ev3 as ev3
import ev3dev.core as ev3core

class CoolInfraredSensor:
    HEADING_CHANNEL = 0
    DISTANCE_CHANNEL = 1
    PROXIMITY_CHANNEL = 0

    def __init__(self):
        self.irs = ev3.InfraredSensor()
        pass

    def measure_proximity(self):
        self.irs.mode = self.irs.MODE_IR_PROX
        return self.irs.value(self.PROXIMITY_CHANNEL)

    def take_bearing(self):
        self.irs.mode = self.irs.MODE_IR_SEEK
        heading = self.irs.value(self.HEADING_CHANNEL)
        self.irs.mode = self.irs.MODE_IR_SEEK
        distance = self.irs.value(self.DISTANCE_CHANNEL)

        if self._is_bad_result(heading, distance):
            return None

        heading = self._normalise_heading(heading)
        return { "heading" : heading, "distance" : distance }

    def _is_bad_result(self, heading, distance):
        return distance == -128 or (heading == 0 and distance == 100)

    def _normalise_heading(self, heading):
        return max(-25, min(25, heading)) / 25.0

class LevelLeds:
    LEFT = ev3.Leds.LEFT
    RIGHT = ev3.Leds.RIGHT
    YELLOW = ev3.Leds.YELLOW
    GREEN = ev3.Leds.GREEN

    def __init__(self):
        self.leds = ev3.Leds()

    def indicate_error(self):
        self.leds.set_color(self.LEFT, self.YELLOW, 0.5)
        self.leds.set_color(self.RIGHT, self.YELLOW, 0.5)

    def indicate_heading(self, heading):
        left_brightness = max(0, heading * 1.0)
        right_brightness = max(0, heading * -1.0)
        self.leds.set_color(self.LEFT, self.GREEN, left_brightness)
        self.leds.set_color(self.RIGHT, self.GREEN, right_brightness)

def main():
    print("Starting...")
    sensor = CoolInfraredSensor()
    leds = LevelLeds()
    print("Devices initialised, entering main loop")

    while True:
        bearing = sensor.take_bearing()

        if bearing is None:
            print("No bearing detected.")
            leds.indicate_error()
        else:
            heading = bearing["heading"]
            leds.indicate_heading(heading)
            print("*" * (int((heading * -1.0 + 1) * 79) + 1))

if __name__ == "__main__":
  main()
